In [1]:
from scipy.sparse import csr_matrix
from numpy import zeros
def MatVec_csr( data:'float[:]' ,  COL_INDEX:'int[:]', ROW_INDEX:'int[:]',x:'float[:]'):
    m=len(x)
    y=zeros(m)
    j=0
    for i in range(m):
        while (j<ROW_INDEX[i+1]):
            y[i] += data[j]*x[COL_INDEX[j]]
            j+=1
    return y


In [2]:
##test
import numpy as np
ROW_INDEX= np.array([0 , 2, 3, 6])
COL_INDEX= np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
m=len(ROW_INDEX)-1

A=csr_matrix((data, COL_INDEX, ROW_INDEX), shape=(m, m)).toarray()
print(A)
x=np.ones(m)
print(MatVec_csr(data,COL_INDEX,ROW_INDEX,x))

print('#################')

print(np.dot(A,x))


    


[[1 0 2]
 [0 0 3]
 [4 5 6]]
[ 3.  3. 15.]
#################
[ 3.  3. 15.]
